Feature/register service connect to server
FlexW/splitbills pull request #1
Opened 2021-03-20 19:07 UTC by tee0paw

2021-03-20 19:26 UTC, FlexW requested changes

2021-03-20 19:26 UTC, FlexW commented on roadmap.org
> -    Friends should show small summary how much user owes or paid.
Unrelated change :)

2021-03-20 19:26 UTC, FlexW commented on src/app/_helpers/fake-backend.ts
> +*/
Please delete fake-backend.ts :)

2021-03-20 19:26 UTC, FlexW commented on src/app/_helpers/index.ts
> +//export * from './fake-backend';
Dito

2021-03-20 19:26 UTC, FlexW commented on src/app/_services/bills.service.spec.ts
> +    service.getBillsWithUsersByUserId().subscribe((result) => {
unrelated

2021-03-20 19:26 UTC, FlexW commented on src/app/_services/bills.service.ts
> +
unrelated

2021-03-20 19:26 UTC, FlexW commented on src/app/_services/bills.service.ts
> +  getBillsWithUsersByUserId(): Observable<BillWithUsers[] | RequestError> {
unrelated

2021-03-20 19:26 UTC, FlexW commented on src/app/_services/bills.service.ts
> +      })
unrelated

2021-03-20 19:26 UTC, FlexW commented on src/app/_services/register.service.ts
> +import { map, catchError, retry } from 'rxjs/operators';
unrelated

2021-03-20 19:26 UTC, FlexW commented on src/app/app.module.ts
> +//import { fakeBackendProvider } from './_helpers';
please remove comment

2021-03-20 19:26 UTC, FlexW commented on src/app/app.module.ts
> +    //fakeBackendProvider,
remove

2021-03-20 19:26 UTC, FlexW commented on src/app/bills/bills.component.ts
> +    });
unrelated

2021-03-20 19:26 UTC, FlexW commented on src/app/group-list-item/group-list-item.component.ts
> +      let style = { color: 'black' };
unrelated

2021-03-21 22:02 UTC, tee0paw commented on src/app/_services/bills.service.spec.ts
> +    service.getBillsWithUsersByUserId().subscribe((result) => {
cannot delete this, this throws error

2021-05-14 11:19 UTC, closed without merging